### ISSUE TITLE
Support of buf.build

### ISSUE THREAD

**Issue by nicolasvac** [ysugimoto/grpc-graphql-gateway#48]
As title says, it would bice nice if this package was compatible with https://buf.build/ remote plugins, like swagger, grpc-gateway and so on.

Thank you, Nicolas.

**Comment by jpfourny** [comment]
Yes!

**Comment by ysugimoto** [comment]
@nicolasvac @jpfourny I'm soooooo sorry for being late reply.
I've just published to BSR https://buf.build/ysugimoto/grpc-graphql-gateway hope this help you.
