### ISSUE TITLE
add source relative option to plugin

### ISSUE THREAD

**Issue by emicklei** [ysugimoto/grpc-graphql-gateway#50]
Hi,

Currently I use the following command to generate files based on a proto file which is using an output option:
```
	protoc \
	-I proto \
	--go_out=todo --go_opt=paths=source_relative \
	--go-grpc_out=todo --go-grpc_opt=paths=source_relative \
	todo.proto
```

To make sure the graphql file is created at the same pkg location, it would be good to support the same option such that this works:

```
	protoc \
	-I proto \
	--go_out=todo --go_opt=paths=source_relative \
	--go-grpc_out=todo --go-grpc_opt=paths=source_relative \
	--graphql_out=todo --go-graphql_opt=paths=source_relative \
	todo.proto
```

**Comment by ysugimoto** [comment]
Hi @emicklei,

Common other plugins seem to support the feature you requested, so I'll implement this feature.
Thank you for your making issue.
