### ISSUE TITLE
This only works with golang?

### ISSUE THREAD

**Issue by isfernand** [ysugimoto/grpc-graphql-gateway#56]
I have a project with .Net 6.0, I would like to use this plugin, but i don't get how to configure it

**Comment by ysugimoto** [comment]
@isfernand Yes, now we support only Golang because the `protoc-gen-graphql` command generates GraphQL gateway code of Golang. https://github.com/ysugimoto/grpc-graphql-gateway/tree/master/protoc-gen-graphql
